apiVersion: v1  
kind: Pod
metadata: 
  name: ussdapp2
spec:
  containers:
  - name:  pehala
    image: nginx
    ports: 
    - containerPort: 80
      hostPort: 1024
  - name:  dusra
    image: tomcat
    ports:
    - containerPort: 8080
      hostPort: 1025
  - name:  tisara
    image: httpd
    ports:
    - containerPort: 80
      hostPort: 1026
  - name:  choutha
    image: ppollai/nginx-freelancer
    ports:
    - containerPort: 80
      hostPort: 1027

