apiVersion: v1  
kind: Pod
metadata: 
  name: xxxx1
spec:
  containers:
  - name:  pehala
    image: nginx
    ports: 
    - containerPort: 80
      hostPort: 1026
  - name:  dusra
    image: tomcat
    ports:
    - containerPort: 8080
      hostPort: 1027

