apiVersion: v1
kind: Pod
metadata:
  name: mycmp1
  labels:
    dep: account
spec:
  containers:
  - name: nginx1
    image: nginx
    ports:
    - containerPort: 80
  - name: tomcat1
    image: tomcat
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: mycmp2
  labels:
    dep: finance
spec:
  containers:
  - name: nginx1
    image: nginx
    ports:
    - containerPort: 80
  - name: tomcat1
    image: tomcat
    ports:
      - containerPort: 8080
