apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    tier: frontend
  ports:
  - port: 1024
    name: nginx
    targetPort: nginxkaport
  - port: 1025
    name: tomcat
    targetPort: tomcatkaport
